#!/usr/bin/env node

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('\n🚀 Localhost Setup Wizard\n');
console.log('This will help you set up the application for local development.\n');

interface Question {
  key: string;
  question: string;
  default: string;
  optional?: boolean;
}

const questions: Question[] = [
  {
    key: 'VITE_FIREBASE_PROJECT_ID',
    question: 'Enter your Firebase Project ID: ',
    default: 'your-project-id'
  },
  {
    key: 'VITE_FIREBASE_API_KEY',
    question: 'Enter your Firebase API Key: ',
    default: 'your_firebase_api_key'
  },
  {
    key: 'OPENAI_API_KEY',
    question: 'Enter your OpenAI API Key (or press Enter to skip): ',
    default: '',
    optional: true
  },
  {
    key: 'GROQ_API_KEY',
    question: 'Enter your Groq API Key (or press Enter to skip): ',
    default: '',
    optional: true
  },
  {
    key: 'GOOGLE_API_KEY',
    question: 'Enter your Google API Key (or press Enter to skip): ',
    default: '',
    optional: true
  }
];

const answers: Record<string, string> = {};
let currentIndex = 0;

function askQuestion(): void {
  if (currentIndex >= questions.length) {
    createEnvFile();
    return;
  }

  const q = questions[currentIndex];
  rl.question(q.question, (answer: string) => {
    answers[q.key] = answer.trim() || q.default;
    currentIndex++;
    askQuestion();
  });
}

function createEnvFile(): void {
  console.log('\n📝 Creating .env file...\n');

  const projectId = answers['VITE_FIREBASE_PROJECT_ID'];
  
  const envContent = `# ============================================
# LOCALHOST DEVELOPMENT CONFIGURATION
# Generated by setup wizard
# ============================================

# Firebase Configuration
VITE_FIREBASE_API_KEY=${answers['VITE_FIREBASE_API_KEY']}
VITE_FIREBASE_AUTH_DOMAIN=${projectId}.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=${projectId}
VITE_FIREBASE_STORAGE_BUCKET=${projectId}.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=123456789
VITE_FIREBASE_APP_ID=1:123456789:web:abcdef

# API URL - Localhost
VITE_API_URL=http://localhost:5001/${projectId}/us-central1/api

# AI Providers
${answers['OPENAI_API_KEY'] ? `OPENAI_API_KEY=${answers['OPENAI_API_KEY']}` : '# OPENAI_API_KEY=sk-your-key-here'}
OPENAI_MODEL=gpt-4-turbo-preview

${answers['GROQ_API_KEY'] ? `GROQ_API_KEY=${answers['GROQ_API_KEY']}` : '# GROQ_API_KEY=gsk_your-key-here'}
GROQ_MODEL=llama-3.1-70b-versatile

${answers['GOOGLE_API_KEY'] ? `GOOGLE_API_KEY=${answers['GOOGLE_API_KEY']}` : '# GOOGLE_API_KEY=your-key-here'}
GOOGLE_MODEL=gemini-1.5-pro

# ANTHROPIC_API_KEY=sk-ant-your-key-here
# ANTHROPIC_MODEL=claude-3-5-sonnet-20241022

# XAI_API_KEY=xai-your-key-here
# XAI_MODEL=grok-beta

# RAG Configuration - Localhost (AI Only)
RAG_ENABLED=true
RAG_STRATEGY=ai_only
RAG_QUESTION_BANK_PERCENTAGE=0
RAG_SIMILARITY_THRESHOLD=0.7

# Rate Limiting - Disabled for Localhost
RATE_LIMIT_ENABLED=false
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# Application
NODE_ENV=development
PORT=5001

# AI Provider Priority
AI_PROVIDER_PRIORITY=openai,groq,google,anthropic,xai
`;

  fs.writeFileSync('.env', envContent);
  console.log('✅ .env file created successfully!\n');

  // Update .firebaserc
  const firebaserc = {
    projects: {
      default: projectId
    }
  };
  
  fs.writeFileSync('.firebaserc', JSON.stringify(firebaserc, null, 2));
  console.log('✅ .firebaserc updated successfully!\n');

  // Check if at least one AI provider is configured
  const hasAIProvider = answers['OPENAI_API_KEY'] || answers['GROQ_API_KEY'] || answers['GOOGLE_API_KEY'];
  
  if (!hasAIProvider) {
    console.log('⚠️  WARNING: No AI provider API key configured!');
    console.log('   You need at least one AI provider to generate questions.');
    console.log('   Edit .env and add an API key before running the app.\n');
  }

  console.log('🎉 Setup complete!\n');
  console.log('Next steps:');
  console.log('1. Enable Authentication in Firebase Console');
  console.log('2. Enable Firestore in Firebase Console (test mode)');
  console.log('3. Run: npm run seed:careers-client');
  console.log('4. Run: npm run dev:client');
  console.log('5. Open: http://localhost:3000\n');
  console.log('For detailed instructions, see LOCALHOST_SETUP.md\n');

  rl.close();
}

// Start the wizard
askQuestion();
